services:
  - type: web
    name: nyc-income
    runtime: python
    plan: free
    buildCommand: |
      python --version
      pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
